### ISSUE TITLE
DateTime Format

### ISSUE THREAD

**Issue by matthewdmanning** [matthewdmanning/flood_data#10]
Data in Hydroshare file does not load properly into pandas dataframe. Can be fixed manually by loading into Excel and changing format. Goal: Use pandas method to transform in script.

**Comment by j23414** [comment]
Talked with the other team and instead of the hydroshare `STORM_data_flooded_streets_2010-2016.csv`, we're supposed to use the github version `db_scripts/STORM_data_flooded_streets_2010-2016.csv`. 

```
python prepare_flood_events_table.py
```

runs without errors so we can stop fetching the csv from hydroshare.

**Comment by j23414** [comment]
Used the github `STORM_data_flooded_streets_2010-2016.csv` data instead
